# Generated by Django 2.2.6 on 2019-10-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('place', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('style', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Singers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default='', max_length=20)),
                ('ages', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.AddField(
            model_name='groups',
            name='singers',
            field=models.ManyToManyField(to='million.Singers'),
        ),
        migrations.AddField(
            model_name='concert',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Groups'),
        ),
    ]
